version: '3'

services:
  delay-server:
    container_name: delay-server
    image: winterchen/delay-server-arrch64
    ports:
      - "8088:8088"
    volumes:
      - "./delay/log:/log"
    args:
      SERVER_PORT: 8088
      SPRING_RABBITMQ_HOST: 127.0.0.1
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: GUEST
      SPRING_RABBITMQ_PASSWORD: GUEST
      SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE-MODE: MANUAL
      SPRING_REDIS_HOST: 127.0.0.1
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ROOT
      SPRING_REDIS_TIMEOUT: 10000
      SPRING_REDIS_DATABASE: 0
      SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE: 8
      SPRING_REDIS_LETTUCE_POOL_MAX_WAIT: -1
      SPRING_REDIS_LETTUCE_POOL_MAX_IDLE: 8
      SPRING_REDIS_LETTUCE_POOL_MIN_IDLE: 0
      COM_WINTERCHEN_FAIL_STORE_STRATEGY_CODE: REDIS

