FROM openjdk:8-jdk-alpine 
VOLUME /tmp
VOLUME /log
ARG SERVER_PORT
ARG SPRING_RABBITMQ_HOST
ARG SPRING_RABBITMQ_PORT
ARG SPRING_RABBITMQ_USERNAME
ARG SPRING_RABBITMQ_PASSWORD
ARG SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE
ARG SPRING_REDIS_HOST
ARG SPRING_REDIS_PORT
ARG SPRING_REDIS_PASSWORD
ARG SPRING_REDIS_TIMEOUT
ARG SPRING_REDIS_DATABASE
ARG SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE
ARG SPRING_REDIS_LETTUCE_POOL_MAX_WAIT
ARG SPRING_REDIS_LETTUCE_POOL_MAX_IDLE
ARG SPRING_REDIS_LETTUCE_POOL_MIN_IDLE
ARG COM_WINTERCHEN_FAIL_STORE_STRATEGY_CODE

ENV LOG_DIR /tmp

ENV JVM_ARGS -server -Xms512m -Xmx1024m \
 -XX:+HeapDumpOnOutOfMemoryError \
 -XX:HeapDumpPath=${LOG_DIR}/dump/dump-yyy.log \
 -XX:ErrorFile=${LOG_DIR}/jvm/jvm-crash.log

ENV PROPERTIES_ARGS -Dserver.port=${SERVER_PORT} -Dspring.rabbitmq.host=${SPRING_RABBITMQ_HOST} \
-Dspring.rabbitmq.port=${SPRING_RABBITMQ_PORT} \
-Dspring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME} \
-Dspring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD} \
-Dspring.rabbitmq.listener.simple.acknowledge-mode=${SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE} \
-Dspring.redis.host=${SPRING_REDIS_HOST} \
-Dspring.redis.port=${SPRING_REDIS_PORT} \
-Dspring.redis.password=${SPRING_REDIS_PASSWORD} \
-Dspring.redis.timeout=${SPRING_REDIS_TIMEOUT} \
-Dspring.redis.database=${SPRING_REDIS_DATABASE} \
-Dspring.redis.lettuce.pool.max-active=${SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE} \
-Dspring.redis.lettuce.pool.max-wait=${SPRING_REDIS_LETTUCE_POOL_MAX_WAIT} \
-Dspring.redis.lettuce.pool.max-idle=${SPRING_REDIS_LETTUCE_POOL_MAX_IDLE} \
-Dspring.redis.lettuce.pool.min-idle=${SPRING_REDIS_LETTUCE_POOL_MIN_IDLE} \
-Dcom.winterchen.fail.store.strategy.code=${COM_WINTERCHEN_FAIL_STORE_STRATEGY_CODE}

ADD delay-server-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT java ${JVM_ARGS} -Djava.security.egd=file:/dev/./urandom  ${PROPERTIES_ARGS} -jar /app.jar
