FROM openjdk:8-jdk-alpine 
VOLUME /tmp
VOLUME /log


ENV LOG_DIR /tmp

ENV JVM_ARGS -server -Xms512m -Xmx1024m \
 -XX:+HeapDumpOnOutOfMemoryError \
 -XX:HeapDumpPath=${LOG_DIR}/dump/dump-yyy.log \
 -XX:ErrorFile=${LOG_DIR}/jvm/jvm-crash.log



ADD delay-server-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT java ${JVM_ARGS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar
